name: gs-udf
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - pillow=10.2.0
  - pip=23.3.1
  - python=3.8.18
  - pytorch=1.12.1
  - torchvision=0.13.1
  - typing_extensions=4.11.0
  - pip:
    - mediapy==1.1.2
    - lpips==0.1.4
    - scikit-image==0.21.0
    - tqdm==4.66.2
    - trimesh==4.3.2
    - submodules/diff-surfel-rasterization
    - submodules/simple-knn
    - submodules/chamfer_dist
    - cython==3.0.11
    - imageio==2.34.0
    - numpy==1.24.4
    - omegaconf==2.3.0
    - open3d==0.10.0.0
    - opencv-python==4.9.0.80
    - plyfile==1.0.3
    - pytorch3d==0.7.5
    - scikit-learn==1.3.2
    - scipy==1.10.1
    - gputil==1.4.0
